# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, validators=[django.core.validators.MinValueValidator(20)])),
                ('content', models.CharField(max_length=150, validators=[django.core.validators.MinValueValidator(20)])),
                ('image_url', models.URLField(validators=[notification.models.image_validator])),
                ('dispatch_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
